server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: product
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    show-sql: false
    database-platform: ${JPA_DIALECT}
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    endpoint:
      health:
        probes:
          enabled: true
        show-details: always
  endpoints:
    web:
      exposure:
        include: health